### ISSUE TITLE
CDATE request

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/SemanticExtraSpecialProperties#109]
### Setup and configuration
- SMW version: 2.5.6
- SESP version: 2.0.0-alpha (bcd3a4c) 07:51, 5 July 2018
- MW version: 1.30.0 (830bb58)
- PHP version: 5.6.38 (apache2handler)
- DB (MySQL etc. and version): 5.5.60-MariaDB

### Feature Request

It would be wonderful if SESP had CDATE to make the page creation date available to go along with CUSER which makes the creation user known

**Comment by kghbln** [comment]
See {here](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Creation_date). An overview of properties provided by SMW is [there](https://www.semantic-mediawiki.org/wiki/Help:Special_properties)

**Comment by revansx** [comment]
Hi kghbln, thanks for the reply. Forgive me if posting this request in 2 locations (here and on the SESP talk page) was inappropriate. It's not clear to me which location is active and I just thought I was being thorough.  

Thanks for linking the info on Special property creation date. Is there any reason why "Creation Date" does not show up on the "Browse Properties" special page for a page? "Modification Date" does. Can you help me understand why these special properties don't appear like other proprties?

**Comment by revansx** [comment]
If I understand you, the ask statement below should work on any page to get the "Creation date" of the Page, but it doesn't return anything on my site. Am I missing something?

`{{#ask:[[{{FULLPAGENAME}}]]|?Creation Date=|mainlabel=-}}`

**Comment by revansx** [comment]
ah!, disabled by default. got it. thank you!

**Comment by revansx** [comment]
$smwgPageSpecialProperties[] = '_CDAT';

w00t!
