### ISSUE TITLE
_USERGROUP and custom rights groups

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/SemanticExtraSpecialProperties#110]
### Setup and configuration
- SMW version: 2.5.6
- SESP version: 2.1.0-alpha (6deea72) 03:01, 17 December 2018
- MW version: 1.30.0 (830bb58) 16:58, 8 December 2017
- PHP version:  5.6.40 (apache2handler)
- DB (MySQL etc. and version): 5.5.60-MariaDB

### Issue

The SESP parameter "_USERGROUP" which adds a property to user pages with the users assigned groups .. works well for built-in mw groups, however, I can not seem to get it to work for custom groups. 

- For example, I add: `$wgGroupPermissions['team-A']['read'] = true;` to my LocalSettings.php and the group exists in the Modify User Rights spacial page 
- I add the user to the group "team-A" and that works well.
- SESP however does not pick up on this custom group.
- Am I missing a step?
- Can someone confirm this.

Ref: https://www.mediawiki.org/wiki/Topic:Uv0p4apl4n25i1wh

**Comment by mwjames** [comment]
Hi,

> - SMW version: 2.5.6
> - SESP version: 2.1.0-alpha (6deea72) 03:01, 17 December 2018

[0] describes the specific requirements for the support of user groups.

[0] https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/pull/100

Cheers

**Comment by kghbln** [comment]
So it is working in the end. However for the jobs to roll in SMW 3.0+ is needed.
