### ISSUE TITLE
No usage docs

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/SemanticExtraSpecialProperties#118]
I cannot find any usage docs for this extension. No info on which properties get added. Sure I saw some technical docs about identifiers, though that does not help a user.

So I'm still wondering myself what the exact names of the added properties are. Guess I have to look at the code.

Or am I really blind and missing the docs?

**Comment by s7eph4n** [comment]
There is https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/docs/configuration.md#labels, but that's rather cumbersome and certainly not unambiguous.

**Comment by JeroenDeDauw** [comment]
Yeah I saw that, but that is technical docs. 

It also says it's easy to go to special:properties. I spend 3 minutes looking at the huge list there and then gave up. Finally got the info I needed by looking at i18n/en.json.

**Comment by mwjames** [comment]
> It also says it's easy to go to special:properties. I spend 3 minutes
> looking at the huge list there and then gave up. Finally got the info I
> needed by looking at i18n/en.json.

I'm still unclear on what you expected to find (or didn't find).

**Comment by JeroenDeDauw** [comment]
A list of property names I could query in the wiki. Like

* Modification date
* Number of revisions

**Comment by kghbln** [comment]
We could indeed map the identifiers to respective property names, however only for English which should be good enough. It is on my list

**Comment by kghbln** [comment]
Fixed with https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/pull/135
