### ISSUE TITLE
Property:Exif:Headling has preferred label "title"?

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticExtraSpecialProperties#120]
### Setup and configuration
- SMW version: 3.0.2
- SESP version: 2.0
- MW version: 1.31.3
- PHP version: 7.1.8
- DB (MySQL etc. and version):  mysql 5.5.62

### Issue
When I activate the extension, predefined property "Exif:Headling" is introduced. It seems to have the preferred label "Title" (in German "Titel") as it comes into conflict with a property named "Titel" already existing in my wiki.

I cannot see where this comes from, as [here](https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/f8a78b434648431359548bca0cd0d7d20a948448/data/definitions.json#L647-L651) the label seems to be Exif:Heading

Does not seem to happen in Sandbox: https://sandbox.semantic-mediawiki.org/wiki/Attribut:Title 
You can see it here: https://testwiki.kdz.eu/Attribut:Titel

**Comment by kghbln** [comment]
Here we are reusing the system messages provided by MediaWiki core. I suggest to either change https://testwiki.kdz.eu/MediaWiki:Exif-headline to something else or to migrate away your property. Sandbox does not have the issue since it is a French language instance.

**Comment by krabina** [comment]
Thank you for the hint! But what is MediaWiki:Exif-headline? I never touched that...
BTW changing https://testwiki.kdz.eu/MediaWiki:Exif-headline did not help. Seems I have to migrate the property...

**Comment by kghbln** [comment]
> Seems I have to migrate the property...

This is the better idea anyways.

> But what is MediaWiki:Exif-headline?

This is the label for the headline contained in the exif data cameras collect. This it the metadata block shown at the bottom of each file page.

**Comment by krabina** [comment]
Maybe SESP should - when set up - check if property names it intends to use are already used and if yes, change the names to Exif-...
