### ISSUE TITLE
Add Exif special properties

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticExtraSpecialProperties#122]
### Feature request
It would be a logical addition to SESP to add properties that are available im image exif data:
https://www.mediawiki.org/wiki/Manual:File_metadata_handling 

This would be a very powerful feature for image handling, because then you could query this data...

![grafik](https://user-images.githubusercontent.com/4318745/64411127-e192bd80-d08c-11e9-8878-5979cb9df707.png)

**Comment by kghbln** [comment]
`_EXIFDATA` is your friend. :)

--> [Property identifiers overview](https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/docs/configuration.md#identifiers)

--> [Example on sandbox](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/:Fichier:NietzscheGod.jpg) EXIFDATA ist a ["container property"](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/:Fichier:NietzscheGod.jpg-23-5FEXIFDATA)
