### ISSUE TITLE
MW 1.34+ Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE'

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#124]
### Setup and configuration

- MediaWiki | 1.34.0-rc.0 (366bf66)22:03, 15 October 2019
- PHP | 7.2.19-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.41-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (c0b7a8f) 17:35, 14 October 2019
- Semantic Extra Special Properties | 2.1.0-alpha (9606083) 07:37, 10 September 2019

### Issue
When trying to run "rebuildElasticIndex.php" I get the following error:
```
Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP) in /../w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php on line 75

Warning: Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP) in /../w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php on line 75
UnexpectedValueException from line 462 of /../w/includes/libs/rdbms/loadbalancer/LoadBalancer.php: Invalid server index index #DB_SLAVE
```
Probably this is killing Elasticsearch replication for the whole wiki.

### Backtrace
```
#0 /../w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(896): Wikimedia\Rdbms\LoadBalancer->getConnectionIndex('DB_SLAVE', Array, 'DB9907120150926...')
#1 /../w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1043): Wikimedia\Rdbms\LoadBalancer->getConnection('DB_SLAVE', Array, 'DB9907120150926...', 0)
#2 /../w/includes/GlobalFunctions.php(2576): Wikimedia\Rdbms\LoadBalancer->getMaintenanceConnectionRef('DB_SLAVE', Array, 'DB9907120150926...')
#3 /../w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php(75): wfGetDB('DB_SLAVE')
#4 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageNumRevisionPropertyAnnotator.php(76): SESP\AppFactory->getConnection()
#5 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageNumRevisionPropertyAnnotator.php(61): SESP\PropertyAnnotators\PageNumRevisionPropertyAnnotator->getPageRevisions(0)
#6 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/DispatchingPropertyAnnotator.php(73): SESP\PropertyAnnotators\PageNumRevisionPropertyAnnotator->addAnnotation(Object(SMW\DIProperty), Object(SMW\SQLStore\EntityStore\StubSemanticData))
#7 /../w/extensions/SemanticExtraSpecialProperties/src/ExtraPropertyAnnotator.php(72): SESP\PropertyAnnotators\DispatchingPropertyAnnotator->addAnnotation(Object(SMW\DIProperty), Object(SMW\SQLStore\EntityStore\StubSemanticData))
#8 /../w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(176): SESP\ExtraPropertyAnnotator->addAnnotation(Object(SMW\SQLStore\EntityStore\StubSemanticData))
#9 /../w/includes/Hooks.php(174): SESP\HookRegistry->SESP\{closure}(Object(SMW\SQLStore\SQLStore), Object(SMW\SQLStore\EntityStore\StubSemanticData))
#10 /../w/includes/Hooks.php(202): Hooks::callHook('SMWStore::updat...', Array, Array, NULL)
#11 /../w/extensions/SemanticMediaWiki/src/Store.php(234): Hooks::run('SMWStore::updat...', Array)
#12 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/FileIndexer.php(409): SMW\Store->updateData(Object(SMW\SQLStore\EntityStore\StubSemanticData))
#13 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(349): SMW\Elastic\Indexer\FileIndexer->SMW\Elastic\Indexer\{closure}()
#14 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(247): SMW\MediaWiki\Deferred\CallableUpdate->runUpdate()
#15 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/TransactionalCallableUpdate.php(168): SMW\MediaWiki\Deferred\CallableUpdate->doUpdate()
#16 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(285): SMW\MediaWiki\Deferred\TransactionalCallableUpdate->doUpdate()
#17 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/FileIndexer.php(418): SMW\MediaWiki\Deferred\CallableUpdate->pushUpdate()
#18 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/FileIndexer.php(305): SMW\Elastic\Indexer\FileIndexer->addAnnotation(Object(SMW\SQLStore\SQLStore), Object(SMW\DIWikiPage))
#19 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder.php(292): SMW\Elastic\Indexer\FileIndexer->index(Object(SMW\DIWikiPage), Object(ForeignAPIFile))
#20 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(378): SMW\Elastic\Indexer\Rebuilder->rebuild('755', Object(SMW\SQLStore\EntityStore\StubSemanticData))
#21 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(335): SMW\Maintenance\RebuildElasticIndex->rebuild_row('755', Object(stdClass), '183447', false)
#22 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(163): SMW\Maintenance\RebuildElasticIndex->rebuild()
#23 /../w/maintenance/doMaintenance.php(99): SMW\Maintenance\RebuildElasticIndex->execute()
#24 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(437): require_once('/var/www/html/s...')
#25 {main}
```

**Comment by JeroenDeDauw** [comment]
I wonder what justified removing these 2 constants. 2 lines saved and work caused in all extensions using the database...

**Comment by kghbln** [comment]
> I wonder what justified removing these 2 constants. 2 lines saved and work caused in all extensions using the database...

Without words. One may think that it is just a matter of changing to `DB_REPLICA` but this would not be backwards compatible. That's why I cannot do the fix. :(

**Comment by s7eph4n** [comment]
> I wonder what justified removing these 2 constants. 2 lines saved and work caused in all extensions using the database...

2 lines saved is good enough.
WMF as an org does a lot of talking, but does not really care about work caused in extensions to actually force their devs to take that into consideration.

**Comment by kghbln** [comment]
So the code change will be done in SMW?! I am afraid that this is beyond my capability either way.

**Comment by JeroenDeDauw** [comment]
We can put this in every extension where the issue occurs. Else they will still fail if you don't have a recent enough SMW.

```php
if ( !defined( DB_SLAVE ) ) {
    define( 'DB_SLAVE', DB_REPLICA );
}
```

**Comment by kghbln** [comment]
I find it unbelievable that is is not possible to overcome this issue with major modifications to the software. This imho out of control.

**Comment by kghbln** [comment]
> I suggest (which only involves SMW related extension) you define
DB_SLAVE in `SemanticMedia.php` (in initExtension or before) when it
is not defined to prevent all SMW extension to belly up hereby
avoiding to require releases for each single one that is plagued by
this issue.

Does this mean that this hast to be done in SMW? I really would like to move forward here, however I am not a PHP developer. Sandbox is at the brink of inoperability.

**Comment by kghbln** [comment]
Probably [here if I understood correctly](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/SemanticMediaWiki.php#L75)

**Comment by alex-mashin** [comment]
> 
> 
> I wonder what justified removing these 2 constants. 2 lines saved and work caused in all extensions using the database...
See this: https://www.mediawiki.org/wiki/Manual_talk:Database_access#Too_Much_Political_Correctness.

**Comment by alex-mashin** [comment]
Should I switch to version 2.1 to have the error corrected?

**Comment by kghbln** [comment]
> Should I switch to version 2.1 to have the error corrected?

Once it is there is should also deal with this issue. I am afraid there currently on working version available for MW 1.34 and later. I also had to pull it from sandbox.

**Comment by mwjames** [comment]
> See this: https://www.mediawiki.org/wiki/Manual_talk:Database_access#Too_Much_Political_Correctness.

The response shows a certain myopia of being absolute indifferent on how extension development works outside the WMF realm where people don't have the luxury (aka. time) to accommodate for changes they think warrants a removal.

Anyway, I suggest to follow the example of [0].

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/commit/bacd90ce1568a3360b6a06888190c87d384a97ca

**Comment by mwjames** [comment]
> Anyway, I suggest to follow the example of [0].

Furthermore:

- Change "MediaWiki 1.27 or later" to "MediaWiki 1.31 or later"
- Change Travis-CI to correspond to the new boundaries
- Merge #132
