### ISSUE TITLE
Provide "sesp-property-***-desc" system messages

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#134]
### Setup and configuration

- MediaWiki | 1.31.6 (c168a3f)14:28, 19 December 2019
- PHP | 7.2.24-0ubuntu0.18.04.1 (apache2handler)
- MariaDB | 10.1.43-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.1.2 (e00b175) 09:42, 12 January 2020
- Semantic Extra Special Properties | 2.0.0 (5a75bb2) 09:33, 12 October 2018

### Issue

Refs: [#msg36899673](https://sourceforge.net/p/semediawiki/mailman/semediawiki-user/thread/E5817A2E-9DD1-42A4-AD6E-862EF55729B9%40icloud.com/#msg36899673)

 Currently not all extra special properties provided by this extension indicate their origin, e.g. [Page ID](https://www.semantic-mediawiki.org/wiki/Property:Page_ID) does whereas [Subpage](https://www.semantic-mediawiki.org/wiki/Property:Subpage) does not.

For the latter and extra special properties showing the same behaviour the "sesp-property-***-desc" system messages are missing and should be provided.

**Comment by kghbln** [comment]
@mwjames I assume that it is just a matter of missing description messages. If so I could take on this task.

**Comment by kghbln** [comment]
I guess https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4493 got triggered by this issue.

In the end however it is indeed just a matter of adding the missing system messages?

**Comment by mwjames** [comment]
> In the end however it is indeed just a matter of adding the missing system messages?

Yes.

> I guess SemanticMediaWiki/SemanticMediaWiki#4493 got triggered by this issue.

I just came across the missing `File attachment` description in SMW core due to some refactoring for the `FileIndexer` and I ended-up creating a test which found the missing ones.
