### ISSUE TITLE
Replace deprecated Hooks::register / Hooks::isRegistered / Hooks::getHandlers

### ISSUE THREAD

**Issue by umherirrender** [SemanticMediaWiki/SemanticExtraSpecialProperties#214]
### Issue

The functions `Hooks::register` / `Hooks::isRegistered` / `Hooks::getHandlers` are soft-deprecated and going to emit warnings, see 
https://phabricator.wikimedia.org/T335536

**Comment by Seb35** [comment]
The PR #229 partially fixed this issue, but it remains occurences of the class Hooks (uncalled by other code, so it’s not very important). I send a PR.

See also #210 which is linked.
