### ISSUE TITLE
Add ability to retrieve user edit count

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#43]
A nice feature will be to have something like `_USEREDITCOUNT` analog to `_USERREG` on user pages to allow extracting the total edit count of a user on the given wiki.

People like statistics and having this on user pages is very much liked by a lot of people and hopefully helps boost what e.g. WMF calls "editor engagement". Personally I find this as interesting as the users registration date provided by a special property which is already implemented.

**Comment by mwjames** [comment]
> A nice feature will be to have something like _USEREDITCOUNT analog to _USERREG on user pages to allow extracting the total edit count of a user on the given wiki.

Would that be an aggregated number from existing knowledge or is that something stored in MW?

**Comment by kghbln** [comment]
This would be the number of edits stored with the [user edit count field of the user table](https://www.mediawiki.org/wiki/Manual:User_table#user_editcount) stored by MW. This number is e.g. shown when one accesses the basic information section on "Special:Preferences".

**Comment by mwjames** [comment]
> number of edits stored with the user edit count field of the user table stored by MW

Use `User::getEditCount` for something like:

```php
	private function getUserEditCount() {
		if ( !$this->isUserPage() ) {
			return;
		}

		$user = $this->loadRegisteredObject( 'UserByPageName', 'User' );
		$count = $user->getEditCount();

		if ( $count ) {
			return new DINumber( $count );
		}
	}
```

**Comment by kghbln** [comment]
Hey, great! I think I should now be able to add this to the extension. Will do a pr soon.

**Comment by mwjames** [comment]
#44 switched to 1.3-alpha

**Comment by kghbln** [comment]
Yeah, pr soon. :( I slightly adapted you code to meet the changes you have done with the commits end of February. This pull request passes the field test. Admittedly I do not really know how to adapt the tests to include this. The integration tests probably fail for an unrelated reason since even the edit to the RELEASE-NOTES fail.

**Comment by mwjames** [comment]
Fixed with a02054821

**Comment by kghbln** [comment]
@JeroenDeDauw Could you please sync the repos for https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/46. Thanks and cheers! (/qqq was already done directly at tw.n.)

**Comment by JeroenDeDauw** [comment]
Synced

**Comment by kghbln** [comment]
Thanks!
