### ISSUE TITLE
Do the 1.3.0 release

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#46]
Now that feature https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/43 rolled in we could think about doing it.

- [x] Wait a fortnight for the translations of the new special property to roll in
- [x] Add info about `_USEREDITCNT` to the "configuration.md" file
- [x] Tag and release

**Comment by kghbln** [comment]
@JeroenDeDauw One more repo sync for the translations and we are cool here.

**Comment by JeroenDeDauw** [comment]
Just did a sync

**Comment by kghbln** [comment]
@JeroenDeDauw Thank you. Released and all in fluffy. Keeping fingers crossed.
