### ISSUE TITLE
1.25 / WikiPage::getCount is gone

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticExtraSpecialProperties#47]
I'm guessing 

https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/src/Annotator/ExtraPropertyAnnotator.php#L206-L209

```
	private function makeNumberOfPageViewsDataItem() {
		if ( !$this->configuration['wgDisableCounters'] && $this->getWikiPage()->getCount() ) {
			return new DINumber( $this->getWikiPage()->getCount() );
		}
	}
```

will fail now that `WikiPage::getCount()` is gone in 1.25 (https://github.com/wikimedia/mediawiki/commit/90d90dad6e4d463b3db425d78f7ed1e084ca0816#diff-a0f7feeaae57e9d2c735c8919c16ad15)

See also https://gerrit.wikimedia.org/r/#/c/221427/.

@kghbln Maybe something to follow-up? / https://www.mediawiki.org/wiki/Extension:HitCounters

**Comment by kghbln** [comment]
Indeed it will be nice to have a check for the presence of the HitCounters extension. Hope to do a field test if both extensions play soon.

**Comment by kghbln** [comment]
Nope, they do not play. SESP creates the respective table for the views however no views a piped into it. The special property for views does not show up.

**Comment by mwjames** [comment]
I expected it to crash since `$this->getWikiPage()->getCount()` would lead to a fatal in 1.25 for when `$GLOBALS['wgDisableCounters'] = true`.

>SESP creates the respective table for the views however no views a piped into it. The special property for views does not show up.

As expected because SESP only looks for  `$this->getWikiPage()->getCount()` and as far as I know `Extension:HitCounters` does not extend `WikiPage::getCount`.

**Comment by kghbln** [comment]
Ah, so the way out should be provided by the HitCounters extension. I will give Mark a ping about it and depending on his assessment we will probably kill this in SESP or not if there is no other way.

**Comment by mwjames** [comment]
@hexmode Any chance of getting Composer support for `Extension:HitCounters` otherwise making the whole `git` download thing in combination with extensions that require `WikiPage::getCount` are going to be a pain.

**Comment by kghbln** [comment]
@mwjames Thanks for pinging @hexmode :)

**Comment by mwjames** [comment]
@hexmode What is the replacement for `WikiPage::getCount`?

**Comment by hexmode** [comment]
> @hexmode What is the replacement for `WikiPage::getCount`?

HitCounters::getCount( $title )

**Comment by hexmode** [comment]
mwjames writes:

> @hexmode Any chance of getting Composer support for
> `Extension:HitCounters`

Certainly, but I don't have time right now.  I'd happily take a patch...

**Comment by cicalese** [comment]
It would be helpful to me for this issue to be resolved. What is the next step in moving it forward? Is composer support in HitCounters the only limitation?

**Comment by kghbln** [comment]
From what I got out of this implementing `HitCounters::getCount( $title )` instead of `WikiPage::getCount` is the thing to be done here. I guess composer support for HitCounters is a nice to have, but will not get the 'number of views' property back.

**Comment by mwjames** [comment]
> What is the next step in moving it forward? Is composer support in HitCounters the only limitation?

It would certainly help to clarify the dependency together with a spaghetti check that contains something like (under the expectation that `HitCounters::getCount` is a stable accessors):

```
		$count = null;

		if ( class_exists( '\HitCounters' ) ) {
			$count = \HitCounters::getCount( $this->getWikiPage()->getTitle() );
		} else {
			$count = $this->getWikiPage()->getCount();
		}

		if ( !$this->configuration['wgDisableCounters'] && is_numeric( $count ) ) {
			return new DINumber( $count );
		}
```

**Comment by hexmode** [comment]
I still don't have time to work on composer support HitCounters, but, as I said, I would take a patch.

It looks like this could be resolved if someone were to create a pull request with the "spaghetti check" that @mwjames suggested.  Or maybe @mwjames was already going to do that?

**Comment by kghbln** [comment]
Adding composter support is probably something for @paladox He worked on the HitCounters extension in the past too. Just a suggestion though.

**Comment by mwjames** [comment]
> Or maybe @mwjames was already going to do that?

No.

**Comment by paladox** [comment]
@kghbln do you mean adding composer support to HitCounters. If so apparently composer support is no longer being added to mediawiki extensions and skins only being used for test per @Legoktm when I tried adding the support to confirmaccount the patch was reverted due to support not being added.

**Comment by kghbln** [comment]
Thanks for the insight @paladox I am in an land of confusion now but I guess this is just the way it is. Dunno what to say or write.

**Comment by kghbln** [comment]
Let's focus on the actual issue: https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/47#issuecomment-138575120

**Comment by mwjames** [comment]
> composer support is no longer being added to mediawiki extensions and skins only being used for test per @Legoktm

>  I am in an land of confusion now but I guess this is just the way it is. Dunno what to say or write.

This what the WMF has decided, this isn't true for SMW or its extension and since we don't adhere a WMF regime we will not stop supporting this just because someone decided to do so.

**Comment by paladox** [comment]
Ok.

**Comment by cicalese** [comment]
So, if I test mwjames' suggested patch above with HitCounters,and it works, and I submit a pull request with the modified code, will the pull request be merged even if HitCounters does not yet support composer?

**Comment by mwjames** [comment]
> ...  and I submit a pull request with the modified code, will the pull request be merged even if ...

Of course (given that tests are passed).

PS: Any contribution and engagement is welcome.

**Comment by cicalese** [comment]
Great! I will do so.

**Comment by cicalese** [comment]
The suggested code worked great with one minor modification to include the HitCounters namespace.

**Comment by JeroenDeDauw** [comment]
@cicalese will you submit this as a pull request?

**Comment by cicalese** [comment]
Sorry! I forgot the last step in creating the pull request. It is submitted now.
