### ISSUE TITLE
PHP Warning:  filemtime(): stat failed

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#60]
**Setup**
* MediaWiki 	- 1.27.0-rc.1 (5462877)
* PHP 	- 5.6.22-0+deb8u1 (apache2handler)
* MariaDB 	- 10.0.25-MariaDB-1~jessie
* SESP - master

on sanbox.s-wm_o.

I wonder why this only happens for "zh-ch.json":

PHP Warning:  filemtime(): stat failed for /.../w/languages/i18n/zh-cn.json in /.../w/extensions/SemanticExtraSpecialProperties/src/Cache/MessageCache.php on line 188

This started [Thu Apr 21 14:51:15.128766 2016] occasionally, on [Thu May 12 02:13:53.579245 2016] it started to flood my error log.

I will now kill the "l10n_cache-zh-cn.cdb" file and see where we go from here. Still figured I should report this.

**Comment by mwjames** [comment]
> PHP Warning: filemtime(): stat failed for

http://stackoverflow.com/questions/13386082/filemtime-warning-stat-failed-for

**Comment by kghbln** [comment]
> I will now kill the "l10n_cache-zh-cn.cdb" file and see where we go from here.

Did not help. Still wondering why this only happens to "zh-cn" but it really populates the error log.

**Comment by mwjames** [comment]
>  Still wondering why this only happens to "zh-cn" but it really populates the error log.

`zh-ch.json` doesn't exist hence it fails to read the file.
