### ISSUE TITLE
Special properties provided are not marked as such

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#69]
### Setup and configuration

- MediaWiki 	1.27.0 (758cd9d) 22:24, 28. Jun. 2016
- PHP 	5.6.24-0+deb8u1 (apache2handler)
- MariaDB 	10.0.26-MariaDB-1~jessie
- Semantic MediaWiki	2.5.0-alpha (570a26b) 12:00, 8. Aug. 2016
- Semantic Extra Special Properties	1.4.0-alpha (f8d34fe) 20:02, 11. Jul. 2016

### Issue

When accessing "Special:Browse" for a page e.g. for [sandbox main](http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/Main_Page) I can easily identify the special properties provided by Semantic MediaWiki. This is not the case for the special properties provided by the "Semantic Extra Special Properties" extension. Thus I suggest that the ``smwbuiltin`` class also gets applied to these.

**Comment by mwjames** [comment]
Properties should provide descriptions about the expected entity representation.

Related https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1791

**Comment by kghbln** [comment]
> Related SemanticMediaWiki/SemanticMediaWiki#1791

This indeed fixed it. Extra special properties now visible as such!
