### ISSUE TITLE
Add special property to track the user groups

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#80]
To have a special property that allows to track the user groups of a (`_USERGRP`) and thus to be able to track users and the groups they are assigned to will be nice. This allows for a more comfortable view than "Special:ListUsers" which is still somewhat painful.

Probably using the [UserFunctions](https://www.mediawiki.org/wiki/Extension:UserFunctions) to annotate the groups to a page is a way out but this will be much more comfortable since more direct.

I guess this may be implemented similarly to the (`_USERREG`) special property with the difference that the user groups are actually stored in a separate table.

Interestingly I have not found an extension which actually allows to expose the user groups on wiki pages.

**Comment by mwjames** [comment]
> To have a special property that allows to track the user groups of a
> (`_USERGRP`) and thus to be able to track users and the groups they are

Don't hit me with a bat in case I'm wrong but [0] might give you the
information you are asking for.

[0] https://github.com/wikimedia/mediawiki/blob/master/includes/user/User.php#L3296-L3305

> I guess this may be implemented similarly to the (`_USERREG`) special
> property with the difference that the user groups are actually stored in a
> separate table.

See the `PropertyAnnotator` services that make use of the USER object.

Cheers

**Comment by kghbln** [comment]
> Probably using the UserFunctions extension to annotate the groups to a page is a way out but this will be much more comfortable since more direct.

Actually on cannot use this since it triggers on the current user. The alternative [WikiUserInfo](https://www.mediawiki.org/wiki/Extension:WikiUserInfo) does not allow confidence.

**Comment by mwjames** [comment]
> Actually one cannot use this since it triggers on the current user

How about you make an extra check on $GLOBALS['wgUser'] and only in case the created user and the logged-in user match, you'll create an annotation with groups found?

**Comment by kghbln** [comment]
I was more referring to the workaround described thus rectifying a misconception.

> How about you make an extra check on $GLOBALS['wgUser'] and only in case the created user and the logged-in user match, you'll create an annotation with groups found?

No, having this for all users is cool and the expected result of the annotation.

**Comment by kghbln** [comment]
A fortnight ago I found the [RightFunctions](https://www.mediawiki.org/wiki/Extension:RightFunctions) extension that allows me to track the user groups not just for the current user but for every specified user. Thus I was able to do a `{{#ifgroup: coordinator |[[Is in user group::Coordinator| ]] | |{{FULLPAGENAME}} }}`. So there is a usable alternative however I would probably be an nice enhancement if SESP could do this directly.
