### ISSUE TITLE
Remove double underscores from special property message keys

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#96]
### Setup and configuration

- SMW version: Semantic MediaWiki | 3.0.0-alpha (469a5b7) 09:10, 7 December 2017
- SESP version: Semantic Extra Special Properties | 2.0.0-alpha (3ce89cc) 07:45, 23 November 2017

### Issue

This issue refers to the issue reported at: https://github.com/SemanticMediaWiki/SemanticCite/issues/58 and tackled in SMW core with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2859.

Necessary since MediaWiki merges two consecutive underscores.

**Comment by kghbln** [comment]
Also noted https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1365

**Comment by alex-mashin** [comment]
The bug seems resolved: there are no double underscores in message keys.
