### ISSUE TITLE
Add support for property grouping

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#97]
Currently special properties provided by this extension are still grouped together with regular properties. This is not wrong, but having a consistent behaviour will be nice.

Refs: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2874

**Comment by mwjames** [comment]
> Currently special properties provided by this extension are still grouped
> together with regular properties. This is not wrong, but having a consistent
> behaviour will be nice.

Looking at [0], one can see that various properties are assigned to a
group including some that are deployed via SESP.

The grouping feature is independent of the property status (user,
predefined etc.) with the only requirement to assign a marked category
(specified with `is property group`) on the property page.

Did I miss something?

[0] https://sandbox.semantic-mediawiki.org/wiki/Cat%C3%A9gorie:Page_group

Cheers

**Comment by kghbln** [comment]
Looking at this [Special:Browse](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/:Lorem-20ipsum) made me think that some extra support is required. Apparently since I only had a very brief peep at this feature quite some time ago I figured some extra work might be necessary. Good to learn that this is not the case. Thanks for the info!
